### ISSUE TITLE
GPS just getting jammed, no new Location

### ISSUE THREAD

**Issue by Narhog** [Mictronics/pluto-gps-sim-win32#6]
Hey,
I'm just generating a new GPS signal via Pluto SDR but the Signal just gets jammed.
`./pluto-gps-sim -e brdc3250.19n -l 39.028225,125.751300,100 -U usb:1.4.5`
What did i do wrong?

**Comment by Mictronics** [comment]
The issue tracker is not here for abuse. You already posted the same question in my other repo and I answered. Don't spam my projects!
